Included rule to pause job when for to delete

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,11 +36,16 @@ jobs:
     steps:
     - name: Remove existing container if exists
       run: |
+        set -e
         CONTAINER_ID=$(curl -s -X GET "https://portainer.carloseduardo.dev/api/endpoints/2/docker/containers/json?all=true" \
         -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" | jq -r '.[] | select(.Names[] == "/5_portfolio") | .Id')
         if [ -n "$CONTAINER_ID" ]; then
-          curl -X DELETE "https://portainer.carloseduardo.dev/api/endpoints/2/docker/containers/$CONTAINER_ID?force=true" \
-          -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}"
+          DELETE_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "https://portainer.carloseduardo.dev/api/endpoints/2/docker/containers/$CONTAINER_ID?force=true" \
+          -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}")
+          if [ "$DELETE_RESPONSE" -ne 204 ]; then
+            echo "Failed to delete container with ID $CONTAINER_ID. HTTP status code: $DELETE_RESPONSE"
+            exit 1
+          fi
         fi
 
   pull-image:
